# Generated by Django 4.2.6 on 2023-10-28 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company_logo_url",
                    models.CharField(
                        default="https://interactive-examples.mdn.mozilla.net/media/examples/grapefruit-slice-332-332.jpg",
                        max_length=1000,
                    ),
                ),
                (
                    "company_stamp_url",
                    models.CharField(
                        default="http://www.pngall.com/wp-content/uploads/2016/07/Sun-Download-PNG.png",
                        max_length=1000,
                    ),
                ),
                (
                    "company_background_image_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("company_description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
