# Generated by Django 4.2.6 on 2023-10-28 17:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='card_owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='maximum_stamps',
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('maximum_stamps', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20, 'maximum amount of stamps is too big')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.cardtype'),
        ),
    ]
